# Generated by Django 2.2.7 on 2019-12-09 23:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Placa_de_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Placa_mae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('processadores_suportados', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd'), ('ambos', 'Intel e AMD')], max_length=50, verbose_name='Processador Suportado')),
                ('slots', models.IntegerField(choices=[('1', '1'), ('2', '2')], verbose_name='Quantidade de Slots')),
                ('memom_suportada', models.IntegerField(choices=[('1', '8'), ('2', '12'), ('3', '16'), ('4', '32'), ('5', '64')], verbose_name='Quantidade de Slots')),
                ('video_integrado', models.BooleanField(default=True, verbose_name='Video integrado')),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('marca', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd'), ('ambos', 'Intel e AMD')], max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Monte_seu_pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_memoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Quantidade de Memoria')),
                ('tamanho_da_memoria', models.CharField(choices=[('1', '4'), ('2', '8'), ('3', '16'), ('4', '32'), ('5', '64')], max_length=50, verbose_name='Tamanho da Memoria')),
                ('Memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Memoria', verbose_name='Memoria Ram')),
                ('placa_de_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Placa_de_video', verbose_name='Placa de Video')),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Placa_mae', verbose_name='Placa mae')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Processador', verbose_name='Processador')),
            ],
        ),
    ]
