# Generated by Django 2.2.7 on 2019-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monte_seu_pc',
            options={'verbose_name': '', 'verbose_name_plural': 's'},
        ),
        migrations.RenameField(
            model_name='monte_seu_pc',
            old_name='Memoria',
            new_name='memoria',
        ),
        migrations.AlterField(
            model_name='monte_seu_pc',
            name='tamanho_da_memoria',
            field=models.CharField(choices=[('1', '4GB'), ('2', '8GB'), ('3', '16GB'), ('4', '32GB'), ('5', '64GB')], max_length=50, verbose_name='Tamanho da Memoria'),
        ),
    ]
