# Generated by Django 2.2.7 on 2019-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0003_auto_20191210_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monte_seu_pc',
            name='tamanho_da_memoria',
            field=models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=50, verbose_name='Tamanho da Memoria'),
        ),
    ]
