# Generated by Django 2.2.7 on 2019-12-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0004_auto_20191210_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monte_seu_pc',
            old_name='qnt_memoria',
            new_name='quantidade_de_memoria',
        ),
    ]
