# Generated by Django 2.2.7 on 2019-12-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0005_auto_20191210_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa_mae',
            name='slots',
            field=models.IntegerField(choices=[('2', '2'), ('4', '4')], verbose_name='Quantidade de Slots'),
        ),
    ]
