# Generated by Django 2.2.7 on 2019-12-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0006_auto_20191215_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa_mae',
            name='memom_suportada',
            field=models.IntegerField(choices=[('1', '8'), ('2', '12'), ('3', '16'), ('4', '32'), ('5', '64')], verbose_name='Memoria suportada'),
        ),
    ]
