# Generated by Django 2.2.7 on 2019-12-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0008_auto_20191215_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa_mae',
            name='memom_suportada',
            field=models.IntegerField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], verbose_name='Memoria suportada'),
        ),
    ]
