# Generated by Django 2.2.7 on 2019-12-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0011_memoria_tamanho_da_memoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoria',
            name='tamanho_da_memoria',
        ),
    ]
